### ISSUE TITLE
No tests found with test runner 'JUnit 5'

### ISSUE THREAD

**Issue by cvgaviao** [Kiskae/compile-testing-extension#2]
Hi, 
I've created an annotation processor and tried to test it with compile-testing and junit 5 (the default in my company) with no luck since it has a compile dependency on junit4.
Then I saw your pull request and I'm trying now with your extension.

But I keep receiving the message in title from eclipse and when running with maven no test is found.

Are you able to use Junit 5 to test your annotation processors ?

**Comment by Kiskae** [comment]
It seems like your testing integration detects the junit4 library on the classpath and defaults using that instead of junit jupiter, causing it to ignore the JUnit5 annotations. Since I myself don't use maven or eclipse I'm not able to say how to fix it but it seems like it would be a common issue which would have a solution posted somewhere.

In addition you should be aware that this library (nor 'CompilationRule' on which it is based) is not required for testing annotation processors, but only used to unit test services that rely on the javax.typing `Types` and `Elements` services. If you want to test a full annotation processor you will need to directly use the [`Compiler`](https://github.com/google/compile-testing/blob/master/src/main/java/com/google/testing/compile/Compiler.java) API since you would need to include your own annotations into the source files.
