### ISSUE TITLE
Illegal state when used with `Nested` JUnit classes

### ISSUE THREAD

**Issue by d** [Kiskae/compile-testing-extension#6]
Basically `afterAll` lifecycle hook is invoked per "test container" and it will put the extension in an unexpected state. A small-ish fix might be to abandon the optimization of one compilation per test suite and just purely use one per test method. A more involved fix that retains the optimization will need to properly handle compilation termination

**Comment by Kiskae** [comment]
It has been a while since I've touched this library, could you provide a minimal test-case that can reproduce this issue since `@Nested` tests do seem to be covered by the original test suite: https://github.com/Kiskae/compile-testing-extension/blob/919018594b5b8ba048b9585f00f3b59bf3fbda75/src/test/java/net/serverpeon/testing/compile/CompilationExtensionTest.java#L77-L81

**Comment by d** [comment]
Hi, I'm driving currently so I can't type in perfect code, but the gist is to have the following structure:

1. A top level class annotated with `@ExtendWith(CompilationExtension.class)`

2. Two sibling nested classes each annotated with `@Nested`, each with an empty test method (annotated with `@Test`)

Boom!

Code snippet will be furnished once it's safe to do so

**Comment by Kiskae** [comment]
Turns out updating the build system took longer than creating a fix for the problem.
#7 should fix the issue.
